sudo: required
services:
  - docker

before_install:
  - docker build -t robihdy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run robihdy/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t robihdy/fib-client ./client
  - docker build -t robihdy/fib-server ./server
  - docker build -t robihdy/fib-worker ./worker
  - docker build -t robihdy/fib-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push robihdy/fib-client
  - docker push robihdy/fib-server
  - docker push robihdy/fib-worker
  - docker push robihdy/fib-nginx
